markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: lanstonpeng
url: lanstonpeng.blogcn.com
description: Testing
twitter: lanstonpeng
github: lanstonpeng
gravatar_url: http://www.gravatar.com/avatar/5a36e8505a29cd56826ccc56bcc1dd2d
